import { type Module, inject } from "langium";
import {
    createDefaultModule,
    createDefaultSharedModule,
    type DefaultSharedModuleContext,
    type LangiumServices,
    type LangiumSharedServices,
    type PartialLangiumServices,
} from "langium/lsp";
import { HfsmGeneratedModule, HfsmGeneratedSharedModule } from "./generated/module.js";
import { HfsmValidator, registerValidationChecks } from "./hfsm-validator.js";
import { HfsmScopeComputation, HfsmScopeProvider } from "./hfsm-scope.js";

/**
 * Declaration of custom services - add your own service classes here.
 */
export type HfsmAddedServices = {
    validation: {
        HfsmValidator: HfsmValidator;
    };
};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type HfsmServices = LangiumServices & HfsmAddedServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const HfsmModule: Module<HfsmServices, PartialLangiumServices & HfsmAddedServices> = {
    validation: {
        HfsmValidator: () => new HfsmValidator(),
    },
    references: {
        ScopeComputation: (services) => new HfsmScopeComputation(services),
        ScopeProvider: (services) => new HfsmScopeProvider(services),
    },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createHfsmServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices;
    Hfsm: HfsmServices;
} {
    const shared = inject(createDefaultSharedModule(context), HfsmGeneratedSharedModule);
    const Hfsm = inject(createDefaultModule({ shared }), HfsmGeneratedModule, HfsmModule);
    shared.ServiceRegistry.register(Hfsm);
    registerValidationChecks(Hfsm);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Hfsm };
}
